#!/bin/sh
#
# this is a fake pkg-config since ffmpeg requires pkg-config if you want to
# include external libraries like libfreetype or libass.  The Android NDK does
# not provide any kind of pkg-config.
BUILD_DIR=$PWD/build

case $1 in
    --version)
        echo "0.29.1"
        ;;
    --exists)
        if [ $3 = "openh264" ]; then
            exit 0
        else
            exit 1
        fi
        ;;
    --cflags)
        echo "-I${BUILD_DIR}/include"
        ;;
    --libs)
        echo "-L${BUILD_DIR}/lib -lopenh264"
        ;;
    *)
        echo "fake pkg-config"
        ;;
esac